### ISSUE TITLE
Could not resolve dependency. Maye @elie29/store is using rxjs 6 instead of 7

### ISSUE THREAD

**Issue by luketych** [elie29/nestjs-kafka-project-github#1]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nestjs-kafka-project@1.0.0
npm ERR! Found: rxjs@7.8.1
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"^7.4.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.3" from @elie29/store@1.0.7
npm ERR! node_modules/@elie29/store
npm ERR!   @elie29/store@"1.0.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/luketych/.npm/_logs/2023-05-21T02_56_33_485Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/luketych/.npm/_logs/2023-05-21T02_56_33_485Z-debug-0.log

**Comment by luketych** [comment]
Got it working using yarn

**Comment by elie29** [comment]
@luketych, you need to update the store to have the new version
